[tool.poetry]
name = "sebo-magic"
version = "0.1.0"
description = ""
authors = ["catsocks <3389801+catsocks@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "sebo_magic.py"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
Wand = "^0.6.11"
click = "^8.1.3"
rembg = "^2.0.30"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0" # code formatter
ruff = "^0.0.253" # linter
poethepoet = "^0.18.1" # task runner
pytest = "^7.2.2"
coverage = "^7.2.1"
isort = "^5.12.0" # sort imports

[tool.poetry.scripts]
magic = "sebo_magic:cli"

[tool.isort]
profile = "black"

[tool.poe.tasks]
black = "black ."
isort = "isort ."
fmt = ["black", "isort"]
lint = "ruff check ."
coverage =  "coverage run -m pytest"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
